from distutils.core import setup

setup(
    name='surtrade_api',
    version='',
    packages=['app', 'app.modules', 'app.modules.auth', 'app.modules.users', 'app.modules.contracts',
              'app.modules.locations', 'env.lib.python2.7.distutils', 'env.lib.python2.7.encodings',
              'env.lib.python2.7.site-packages.jwt', 'env.lib.python2.7.site-packages.jwt.contrib',
              'env.lib.python2.7.site-packages.jwt.contrib.algorithms', 'env.lib.python2.7.site-packages.pip',
              'env.lib.python2.7.site-packages.pip.req', 'env.lib.python2.7.site-packages.pip.vcs',
              'env.lib.python2.7.site-packages.pip.utils', 'env.lib.python2.7.site-packages.pip.compat',
              'env.lib.python2.7.site-packages.pip.models', 'env.lib.python2.7.site-packages.pip._vendor',
              'env.lib.python2.7.site-packages.pip._vendor.distlib',
              'env.lib.python2.7.site-packages.pip._vendor.distlib._backport',
              'env.lib.python2.7.site-packages.pip._vendor.colorama',
              'env.lib.python2.7.site-packages.pip._vendor.html5lib',
              'env.lib.python2.7.site-packages.pip._vendor.html5lib._trie',
              'env.lib.python2.7.site-packages.pip._vendor.html5lib.filters',
              'env.lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
              'env.lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
              'env.lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
              'env.lib.python2.7.site-packages.pip._vendor.lockfile',
              'env.lib.python2.7.site-packages.pip._vendor.progress',
              'env.lib.python2.7.site-packages.pip._vendor.requests',
              'env.lib.python2.7.site-packages.pip._vendor.requests.packages',
              'env.lib.python2.7.site-packages.pip._vendor.requests.packages.chardet',
              'env.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3',
              'env.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.util',
              'env.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'env.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'env.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'env.lib.python2.7.site-packages.pip._vendor.packaging',
              'env.lib.python2.7.site-packages.pip._vendor.cachecontrol',
              'env.lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
              'env.lib.python2.7.site-packages.pip._vendor.webencodings',
              'env.lib.python2.7.site-packages.pip._vendor.pkg_resources',
              'env.lib.python2.7.site-packages.pip.commands', 'env.lib.python2.7.site-packages.pip.operations',
              'env.lib.python2.7.site-packages.cffi', 'env.lib.python2.7.site-packages.enum',
              'env.lib.python2.7.site-packages.idna', 'env.lib.python2.7.site-packages.mako',
              'env.lib.python2.7.site-packages.mako.ext', 'env.lib.python2.7.site-packages.click',
              'env.lib.python2.7.site-packages.flask', 'env.lib.python2.7.site-packages.flask.ext',
              'env.lib.python2.7.site-packages.wheel', 'env.lib.python2.7.site-packages.wheel.test',
              'env.lib.python2.7.site-packages.wheel.test.simple.dist.simpledist',
              'env.lib.python2.7.site-packages.wheel.test.complex-dist.complexdist',
              'env.lib.python2.7.site-packages.wheel.tool', 'env.lib.python2.7.site-packages.wheel.signatures',
              'env.lib.python2.7.site-packages.bcrypt', 'env.lib.python2.7.site-packages.jinja2',
              'env.lib.python2.7.site-packages.pyasn1', 'env.lib.python2.7.site-packages.pyasn1.type',
              'env.lib.python2.7.site-packages.pyasn1.codec', 'env.lib.python2.7.site-packages.pyasn1.codec.ber',
              'env.lib.python2.7.site-packages.pyasn1.codec.cer', 'env.lib.python2.7.site-packages.pyasn1.codec.der',
              'env.lib.python2.7.site-packages.pyasn1.codec.native', 'env.lib.python2.7.site-packages.pyasn1.compat',
              'env.lib.python2.7.site-packages.alembic', 'env.lib.python2.7.site-packages.alembic.ddl',
              'env.lib.python2.7.site-packages.alembic.util', 'env.lib.python2.7.site-packages.alembic.script',
              'env.lib.python2.7.site-packages.alembic.runtime', 'env.lib.python2.7.site-packages.alembic.testing',
              'env.lib.python2.7.site-packages.alembic.testing.plugin',
              'env.lib.python2.7.site-packages.alembic.operations',
              'env.lib.python2.7.site-packages.alembic.autogenerate', 'env.lib.python2.7.site-packages.certifi',
              'env.lib.python2.7.site-packages.chardet', 'env.lib.python2.7.site-packages.chardet.cli',
              'env.lib.python2.7.site-packages.urllib3', 'env.lib.python2.7.site-packages.urllib3.util',
              'env.lib.python2.7.site-packages.urllib3.contrib',
              'env.lib.python2.7.site-packages.urllib3.contrib._securetransport',
              'env.lib.python2.7.site-packages.urllib3.packages',
              'env.lib.python2.7.site-packages.urllib3.packages.backports',
              'env.lib.python2.7.site-packages.urllib3.packages.ssl_match_hostname',
              'env.lib.python2.7.site-packages.dateutil', 'env.lib.python2.7.site-packages.dateutil.tz',
              'env.lib.python2.7.site-packages.dateutil.zoneinfo', 'env.lib.python2.7.site-packages.psycopg2',
              'env.lib.python2.7.site-packages.psycopg2.tests', 'env.lib.python2.7.site-packages.requests',
              'env.lib.python2.7.site-packages.werkzeug', 'env.lib.python2.7.site-packages.werkzeug.debug',
              'env.lib.python2.7.site-packages.werkzeug.contrib', 'env.lib.python2.7.site-packages.flask_api',
              'env.lib.python2.7.site-packages.flask_api.tests', 'env.lib.python2.7.site-packages.pycparser',
              'env.lib.python2.7.site-packages.pycparser.ply', 'env.lib.python2.7.site-packages.googlemaps',
              'env.lib.python2.7.site-packages.markupsafe', 'env.lib.python2.7.site-packages.setuptools',
              'env.lib.python2.7.site-packages.setuptools.extern', 'env.lib.python2.7.site-packages.setuptools.command',
              'env.lib.python2.7.site-packages.sqlalchemy', 'env.lib.python2.7.site-packages.sqlalchemy.ext',
              'env.lib.python2.7.site-packages.sqlalchemy.ext.declarative',
              'env.lib.python2.7.site-packages.sqlalchemy.orm', 'env.lib.python2.7.site-packages.sqlalchemy.sql',
              'env.lib.python2.7.site-packages.sqlalchemy.util', 'env.lib.python2.7.site-packages.sqlalchemy.event',
              'env.lib.python2.7.site-packages.sqlalchemy.engine', 'env.lib.python2.7.site-packages.sqlalchemy.testing',
              'env.lib.python2.7.site-packages.sqlalchemy.testing.suite',
              'env.lib.python2.7.site-packages.sqlalchemy.testing.plugin',
              'env.lib.python2.7.site-packages.sqlalchemy.dialects',
              'env.lib.python2.7.site-packages.sqlalchemy.dialects.mssql',
              'env.lib.python2.7.site-packages.sqlalchemy.dialects.mysql',
              'env.lib.python2.7.site-packages.sqlalchemy.dialects.oracle',
              'env.lib.python2.7.site-packages.sqlalchemy.dialects.sqlite',
              'env.lib.python2.7.site-packages.sqlalchemy.dialects.sybase',
              'env.lib.python2.7.site-packages.sqlalchemy.dialects.firebird',
              'env.lib.python2.7.site-packages.sqlalchemy.dialects.postgresql',
              'env.lib.python2.7.site-packages.sqlalchemy.databases',
              'env.lib.python2.7.site-packages.sqlalchemy.connectors', 'env.lib.python2.7.site-packages.cryptography',
              'env.lib.python2.7.site-packages.cryptography.x509',
              'env.lib.python2.7.site-packages.cryptography.hazmat',
              'env.lib.python2.7.site-packages.cryptography.hazmat.backends',
              'env.lib.python2.7.site-packages.cryptography.hazmat.backends.openssl',
              'env.lib.python2.7.site-packages.cryptography.hazmat.backends.commoncrypto',
              'env.lib.python2.7.site-packages.cryptography.hazmat.bindings',
              'env.lib.python2.7.site-packages.cryptography.hazmat.bindings.openssl',
              'env.lib.python2.7.site-packages.cryptography.hazmat.bindings.commoncrypto',
              'env.lib.python2.7.site-packages.cryptography.hazmat.primitives',
              'env.lib.python2.7.site-packages.cryptography.hazmat.primitives.kdf',
              'env.lib.python2.7.site-packages.cryptography.hazmat.primitives.ciphers',
              'env.lib.python2.7.site-packages.cryptography.hazmat.primitives.twofactor',
              'env.lib.python2.7.site-packages.cryptography.hazmat.primitives.asymmetric',
              'env.lib.python2.7.site-packages.cryptography.hazmat.primitives.interfaces',
              'env.lib.python2.7.site-packages.flask_script', 'env.lib.python2.7.site-packages.flask_migrate',
              'env.lib.python2.7.site-packages.pkg_resources', 'env.lib.python2.7.site-packages.pkg_resources.extern',
              'env.lib.python2.7.site-packages.pkg_resources._vendor',
              'env.lib.python2.7.site-packages.pkg_resources._vendor.packaging',
              'env.lib.python2.7.site-packages.flask_sqlalchemy', 'instance'],
    url='',
    license='',
    author='Surtrade',
    author_email='',
    description=''
)
