"""empty message

Revision ID: 5ecc3e79d46a
Revises: fa18da9b87cb
Create Date: 2017-08-01 12:10:19.652298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ecc3e79d46a'
down_revision = 'fa18da9b87cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('auto_authorize', sa.Boolean(), nullable=True),
    sa.Column('expire', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'agent_id')
    )
    op.drop_table('contract')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract',
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('auto_authorize', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('expire', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], [u'agent.id'], name=u'contract_agent_id_fkey'),
    sa.ForeignKeyConstraint(['customer_id'], [u'customer.id'], name=u'contract_customer_id_fkey'),
    sa.PrimaryKeyConstraint('customer_id', 'agent_id', name=u'contract_pkey')
    )
    op.drop_table('contracts')
    # ### end Alembic commands ###
